def javaProjects = [
    project(":apps:credit-card-validator"),
    project(":apps:dream-shops")
]

configure(javaProjects) {
    println "${project.name}"
    apply plugin: 'application'
    version '1.0.0'
    
    repositories {
        mavenCentral()
    }

    dependencies {

    }

    test {
        useJUnitPlatform()
    }
}